FROM node:10-alpine

RUN apk add --no-cache git

ARG SCRIPT
ENV SCRIPT ${SCRIPT}
WORKDIR /opt/backend
EXPOSE 3000

ADD src/api/package.json ./src/api/package.json
ADD src/api/package-lock.json ./src/api/package-lock.json
RUN cd src/api && npm install

COPY ./tsconfig.json .
COPY ./src/api ./src/api
COPY ./src/common ./src/common

WORKDIR /opt/backend/src/api
CMD npx webpack --watch
